export const enum RouterName {
  Home = "/home",
  MusicInfo = "/MusicInfo",
  Info = "/Info",
  Song = "/song",
  Singer = "/singer",
  SongList = "/songList",
  ListSong = "/listSong",
  Comment = "/Comment",
  Consumer = "/consumer",
  Collect = "/collect",
  Error = "/404",
  SignIn = "/",
  SignOut = "0",
}
